spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.MYSQL_BOARDTEST_DATABASE_NAME }}
    username: ${{ secrets.MYSQL_USER_NAME }}
    password: ${{ secrets.MYSQL_USER_PASSWORD }}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect